image: christianbladescb/aglio

pages:
  script:
  - mkdir .public
  - docker run -v $(pwd):/tmp -t christianbladescb/aglio -i /tmp/doc/input.apib -o /tmp/doc/index.html
  - cp -r doc/index.html .public
  - mv .public public
  artifacts:
    paths:
    - public
  only:
  - master